
ARG NODE_VERSION 
FROM node:$NODE_VERSION
RUN apk --no-cache add git

ARG GITHUB_USER 
ARG SERVER_PORT 
ARG INSPECT_PORT 
ARG GITHUB_LINK 
ARG GITHUB_BRANCH 
ARG GIT_WEBHOOK_PORT 

RUN echo $GITHUB_BRANCH $GITHUB_LINK $INSPECT_PORT $NODE_VERSION

WORKDIR /app

#RUN npm install -g npm

RUN npm install pm2 -g

RUN git clone -b main https://github.com/steffenreimann/NodeJS-PM2-Docker-Example.git /app/Watcher
WORKDIR /app/Watcher/
RUN npm install

RUN echo $GITHUB_BRANCH $GITHUB_LINK

RUN git clone -b $GITHUB_BRANCH $GITHUB_LINK /app/Server
WORKDIR /app/Server/
RUN npm install

EXPOSE $SERVER_PORT
EXPOSE $INSPECT_PORT
EXPOSE $GIT_WEBHOOK_PORT

ENV GITHUB_LINK $GITHUB_LINK
ENV GITHUB_BRANCH $GITHUB_BRANCH
ENV GIT_WEBHOOK_PORT $GIT_WEBHOOK_PORT
ENV INSPECT_PORT $INSPECT_PORT
ENV SERVER_PORT $SERVER_PORT

WORKDIR /app/

CMD ["pm2-runtime", "./Watcher/ecosystem.config.js"]
